<../../mkconfig

TARG=\
	prompt.dis\
	secstore.dis\

SYSMODULES=\
	arg.m\
	draw.m\
	dial.m\
	keyboard.m\
	secstore.m\
	string.m\
	sys.m\
	tk.m\
	tkclient.m\

DISBIN=$ROOT/dis/wm

<$ROOT/mkfiles/mkdis
